// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue, ReducerArgsAdapter, SumTypeVariant, Serializer, Identity, ReducerEvent } from "@clockworklabs/spacetimedb-sdk";

export class CreateThingReducer
{
	public static call(_contentArg: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
		const serializer = __SPACETIMEDB__.spacetimeDBClient.getSerializer();
		let _contentArgType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		serializer.write(_contentArgType, _contentArg);
			__SPACETIMEDB__.spacetimeDBClient.call("create_thing", serializer);
		}
	}

	public static deserializeArgs(adapter: ReducerArgsAdapter): any[] {
		let contentArgType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let contentArgValue = AlgebraicValue.deserialize(contentArgType, adapter.next())
		let contentArg = contentArgValue.asString();
		return [contentArg];
	}

	public static on(callback: (reducerEvent: ReducerEvent, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:CreateThing", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("CreateThing", CreateThingReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("CreateThing", CreateThingReducer);
}

export default CreateThingReducer
