// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue, ReducerArgsAdapter, SumTypeVariant, Serializer, Identity, ReducerEvent } from "@clockworklabs/spacetimedb-sdk";

export class UpdateThingContentReducer
{
	public static call(_id: number, _newContent: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
		const serializer = __SPACETIMEDB__.spacetimeDBClient.getSerializer();
		let _idType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U64);
		serializer.write(_idType, _id);
		let _newContentType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		serializer.write(_newContentType, _newContent);
			__SPACETIMEDB__.spacetimeDBClient.call("update_thing_content", serializer);
		}
	}

	public static deserializeArgs(adapter: ReducerArgsAdapter): any[] {
		let idType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U64);
		let idValue = AlgebraicValue.deserialize(idType, adapter.next())
		let id = idValue.asNumber();
		let newContentType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let newContentValue = AlgebraicValue.deserialize(newContentType, adapter.next())
		let newContent = newContentValue.asString();
		return [id, newContent];
	}

	public static on(callback: (reducerEvent: ReducerEvent, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:UpdateThingContent", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("UpdateThingContent", UpdateThingContentReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("UpdateThingContent", UpdateThingContentReducer);
}

export default UpdateThingContentReducer
